name: Build and push Docker images on release

on:
  release:
    types: [published, edited]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.7.0

      - name: Login to DockerHub
        uses: docker/login-action@v2.2.0 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract tag name
        id: get_tag
        run: echo ::set-output name=VERSION::version-${GITHUB_REF#refs/tags/v}

      - name: Build and push
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: hummingbot/hummingbot:${{ steps.get_tag.outputs.VERSION }}
